name: CD pipeline
 
on:
  push:
    branches: [ develop ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Node v12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        
    - name: Grant execute permissions for gradlew
      run:  chmod +x gradlew
        
    - name: Build and Test with Gradle
      run: ./gradlew 
      
    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: human-resources-management
        environment_name: Humanresourcesmanagement-env
        version_label: ${{github.SHA}}
        region: us-east-2
        deployment_package: spring-app/build/libs/hrm-1.0.0.jar
